
# Mybatis 配置
mybatis:
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:cn/mapper/*/*Mapper.xml
  type-aliases-package: cn.agriculture.entity


spring:
  mvc:
    view:
      prefix: /WEB-INF/webpage/
      suffix: .jsp
  thymeleaf: #关闭默认模板引擎
    cache: false #关闭缓存
    enabled: false
  datasource:
    name: druid
    url: jdbc:mysql://192.168.1.8:3306/agrlculture?useAffectedRows=TRUE&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=128&prepStmtCacheSqlLimit=256&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 15
      maxActive: 60
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
  devtools:
    restart: #热部署生效
      enabled: true
      #additional-paths: src/main/java   #设置重启的目录
      #classpath   #目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

  #Redis配置
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    password: 123456
    port: 6379  # Redis服务器连接端口
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000  # 连接超时时间（毫秒）

#      打印执行的sql到控制台
logging:
  level:
    cn.agriculture.dao: debug

#阿里云OOS配置
aliyun:
  bucketName: "bucketName"
  accessKeyId: "accessKeyId"
  accessKeySecret: "accessKeySecret"
  #OSS对应的区域
  endpoint: http://oss-cn-beijing.aliyuncs.com

server:
  tomcat:
    max-http-post-size: -1

